module anchor.core {
	requires lombok;
	requires transitive java.desktop;
	requires transitive colt;
	requires path.pattern.finder;
	requires org.apache.commons.io;
	requires commons.lang;
	requires org.apache.commons.lang3;
	requires org.apache.commons.collections4;
	requires com.google.common;
	requires xstream;
	requires java.compiler;
	exports org.anchoranalysis.core;
	exports org.anchoranalysis.core.cache;
	exports org.anchoranalysis.core.collection;
	exports org.anchoranalysis.core.color;
	exports org.anchoranalysis.core.exception;
	exports org.anchoranalysis.core.exception.combinable;
	exports org.anchoranalysis.core.exception.friendly;
	exports org.anchoranalysis.core.format;
	exports org.anchoranalysis.core.functional;
	exports org.anchoranalysis.core.functional.checked;
	exports org.anchoranalysis.core.functional.unchecked;
	exports org.anchoranalysis.core.graph;
	exports org.anchoranalysis.core.identifier.getter;
	exports org.anchoranalysis.core.identifier.name;
	exports org.anchoranalysis.core.identifier.provider;
	exports org.anchoranalysis.core.identifier.provider.store;
	exports org.anchoranalysis.core.index;
	exports org.anchoranalysis.core.index.range;
	exports org.anchoranalysis.core.log;
	exports org.anchoranalysis.core.log.error;
	exports org.anchoranalysis.core.random;
	exports org.anchoranalysis.core.serialize;
	exports org.anchoranalysis.core.system;
	exports org.anchoranalysis.core.system.path;
	exports org.anchoranalysis.core.time;
	exports org.anchoranalysis.core.value;
}