# 
# This workflow will build and test a Java project with Maven.
#
# It is only triggered on dev branch.
#
# The Maven and SonarCloud working directories are cached for future reuse, as downloading all packages from scratch takes significant time.
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#

name: Java CI with Maven for Development

on:
  push:
    branches:
      - dev

jobs:
  test_Linux_JDK_8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-jdk8
        restore-keys: ${{ runner.os }}-m2
    - name: Create settings.xml for Maven
      uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: |
            [{
                "id": "github_path_path_finder",
                "username": "$GITHUB_ACTOR",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]    
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -Dmaven.test.failure.ignore=true --batch-mode --update-snapshots verify
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_test_failures: true
        fail_if_no_tests: false
        check_name: Test Report - Linux JDK 8
 
  test_Windows_JDK_8:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-jdk8
        restore-keys: ${{ runner.os }}-m2
    - name: Create settings.xml for Maven
      uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: |
            [{
                "id": "github_path_path_finder",
                "username": "$GITHUB_ACTOR",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]    
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -DtestFailureIgnore --batch-mode --update-snapshots verify
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_test_failures: true
        fail_if_no_tests: false
        check_name: Test Report - Windows JDK 8
   
  test_MacOS_JDK_8:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-jdk8
        restore-keys: ${{ runner.os }}-m2
    - name: Create settings.xml for Maven
      uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: |
            [{
                "id": "github_path_path_finder",
                "username": "$GITHUB_ACTOR",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]    
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -Dmaven.test.failure.ignore=true --batch-mode --update-snapshots verify
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_test_failures: true 
        fail_if_no_tests: false
        check_name: Test Report - MacOS JDK 8        
